---
- name: wen's mac os setup
  hosts: local
  connection: local
  roles:
    - macos
  vars_prompt:
    - name: "world_dir"
      prompt: "[ optional ] Where do you want to organize your projects?"
      default: "~/world"
    - name: "dotfiles_repo"
      prompt: "[ optional ] What is your dotfiles https git uri"


