---
# Install with brew cask
- block:
  - name: Install brew casks ( some cask requires password )
    homebrew_cask:
      name: "{{ item }}"
      state: present
      install_options: force
    loop: "{{ brew_casks }}"
    ignore_errors: True
    register: casks
