---
- name: Is iterm2 installed?
  stat:
    path: "{{ applications_dir }}/iTerm.app"
  register: iterm2

- name: Install iterm2
  homebrew_cask:
    name: iterm2
    state: present
  when: not iterm2.stat.exists
