---
# [ Required ]
- import_tasks: dotfiles.yml

# [ Optional ]
# Comment tasks to disable.
- import_tasks: chrome.yml
- import_tasks: vim.yml
- import_tasks: tmux.yml
- import_tasks: iterm2.yml
- import_tasks: shiftit.yml

- import_tasks: conf.d/git.yml
- import_tasks: conf.d/vim.yml
- import_tasks: conf.d/bash.yml
- import_tasks: conf.d/tmux.yml
- import_tasks: conf.d/ideavim.yml
- import_tasks: conf.d/screen.yml
