---
- name: Include dotfiles variables.
  include_vars:
    file: dotfiles.yml

- name: Have a .bashrc?
  stat:
    path: "{{ dotfiles_bashrc }}"
  register: bashrc

- name: Link .bashrc
  file:
    src: "{{ dotfiles_bashrc}}"
    dest: ~/.bashrc
    state: link
  when: bashrc.stat.exists

- name: Have a .bash_profile?
  stat:
    path: "{{ dotfiles_bash_profile }}"
  register: bash_profile

- name: Link .bash_profile
  file:
    src: "{{ dotfiles_bash_profile}}"
    dest: ~/.bash_profile
    state: link
  when: bash_profile.stat.exists
