---
- name: Have a .screenrc?
  stat:
    path: "{{ dotfiles_dir }}/.screenrc"
  register: screenrc

- name: Link .screenrc
  file:
    src: "{{ dotfiles_dir }}/.screenrc"
    dest: ~/.screenrc
    state: link
  when: screenrc.stat.exists
