---
- name: Include dotfiles variables.
  include_vars:
    file: dotfiles.yml

- name: Have a .vimrc?
  stat:
    path: "{{ dotfiles_vimrc }}"
  register: vimrc

- name: Link .vimrc
  file:
    src: "{{ dotfiles_vimrc }}"
    dest: ~/.vimrc
    state: link
  when: vimrc.stat.exists

- name: Use vundle to manage vim plugins?
  shell: "grep \"$call vundle#begin()\" ~/.vimrc"
  ignore_errors: yes
  register: use_vundle
  when: vimrc.stat.exists

- name: Install vundle plugins
  shell: vim +PluginInstall +qall
  when: vimrc.stat.exists and use_vundle.rc == 0



